#%RAML 1.0 DataType
(package): BusinessUnit
(docs-uri): https://docs.commercetools.com/api/projects/business-units#associate
displayName: Associate
properties:
  associateRoleAssignments:
    type: AssociateRoleAssignment[]
    description: |
      Roles assignment to the Associate within the Business Unit.
  roles:
    type: AssociateRoleDeprecated[]
    description: |
      Deprecated type. Use `associateRoleAssignment` instead.
  customer:
    type: CustomerReference
    description: |
      The [Customer](ctp:api:type:Customer) that is part of the Business Unit.
