#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#replicacartdraft
displayName: ReplicaCartDraft
type: object
properties:
  reference:
    type: CartReference | OrderReference
    description: |
      [Reference](ctp:api:type:Reference) to a [Cart](ctp:api:type:Cart) or an [Order](ctp:api:type:Order).
  key?:
    type: string
    description: User-specific unique identifier of the Cart.
