#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#associaterolenamechangedmessage
type: MessagePayload
displayName: AssociateRoleNameChangedMessagePayload
discriminatorValue: AssociateRoleNameChanged
description: |
  Generated after a successful [Set Name](ctp:api:type:AssociateRoleSetNameAction) update action.
properties:
  name:
    type: string
    description: |
      Updated name of the [AssociateRole](ctp:api:type:AssociateRole).
