@startuml

hide methods
enum OrderPermission {
    CREATE_MY_ORDERS_FROM_MY_CARTS
    CREATE_ORDERS_FROM_OTHERS_CARTS
    CREATE_MY_ORDERS_FROM_MY_QUOTES
    CREATE_ORDERS_FROM_OTHERS_QUOTES
    UPDATE_MY_ORDERS
    UPDATE_OTHERS_ORDERS
    VIEW_MY_ORDERS
    VIEW_OTHERS_ORDERS
}


@enduml
