@startuml

hide methods
enum QuoteRequestPermission {
    CREATE_MY_QUOTE_REQUESTS_FROM_MY_CARTS
    CREATE_QUOTE_REQUESTS_FROM_OTHERS_CARTS
    UPDATE_MY_QUOTE_REQUESTS
    UPDATE_OTHERS_QUOTE_REQUESTS
    VIEW_MY_QUOTE_REQUESTS
    VIEW_OTHERS_QUOTE_REQUESTS
}


@enduml
