@startuml

hide methods
enum QuotePermission {
    ACCEPT_MY_QUOTES
    ACCEPT_OTHERS_QUOTES
    DECLINE_MY_QUOTES
    DECLINE_OTHERS_QUOTES
    RENEGOTIATE_MY_QUOTES
    RENEGOTIATE_OTHERS_QUOTES
    VIEW_MY_QUOTES
    VIEW_OTHERS_QUOTES
}


@enduml
